# Expected output:
# > $CRONTAB
# >
test-cron:
  build: .
  entrypoint: bash -x /entrypoint.sh
  command: 'crontab -u root -l'
  environment:
    CRON_OWNER: root
    CRON_ENV_FILE: /var/env.cron
    CRON_TAB: |
      * *    * * *    . /var/env.cron; env; touch /.cron; echo Cron fired at $$(date)
    TZ: Pacific/Auckland

# Expected output:
# > no crontab for root
# Or a blank line
# >
test-no-cron:
  build: .
  entrypoint: bash -x /entrypoint.sh
  command: 'crontab -l'

test-env:
  build: .
  entrypoint: bash -x /entrypoint.sh
  command: 'crontab -l'
  environment:
    TEST: only vars begining with "CRON" are stored.
    CRON_ENV_FILE: /var/cron.env
    CRON_TAB: |
      * *    * * *    . /var/cron.env; env

cron:
  build: .
  environment:
    CRON_ENV_FILE: /var/env.cron
    CRON_TAB: |
      * *    * * *    . /var/env.cron; env
    TZ: Pacific/Auckland
  volumes:
    - /var/mail

mail:
  image: debian:stable
  command: bash -c 'while ! tail -F /var/mail/*; do sleep 1; done'
  volumes_from:
    - cron
